include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_late: true
    # Deliberately NOT enforcing always_use_package_imports to allow ../lib imports from test