name: animalia_arcana
description: A mystical animal tarot app with dark theme and beautiful UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  uuid: ^4.2.1
  flutter_staggered_animations: ^1.1.1
  go_router: ^14.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  share_plus: ^7.2.1
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/decks/
    - assets/spreads/
    - assets/themes/
    - assets/images/
    - assets/images/cards/